// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrmRiD0qoDwr5vln_jeoE3ranwdOuceHE',
    appId: '1:974845475666:web:bd3918b8a1ee4c8d25d88b',
    messagingSenderId: '974845475666',
    projectId: 'wordquiz-8ca30',
    authDomain: 'wordquiz-8ca30.firebaseapp.com',
    storageBucket: 'wordquiz-8ca30.firebasestorage.app',
    measurementId: 'G-92DX1XYPW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzC3iTS5XJUy04cuoSprs5Rw792UrkO34',
    appId: '1:974845475666:android:9984fd71041d5c6025d88b',
    messagingSenderId: '974845475666',
    projectId: 'wordquiz-8ca30',
    storageBucket: 'wordquiz-8ca30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Cqz1MrGOCbgErldRb3pOiTwCixVCbTM',
    appId: '1:974845475666:ios:9991351c2c09091a25d88b',
    messagingSenderId: '974845475666',
    projectId: 'wordquiz-8ca30',
    storageBucket: 'wordquiz-8ca30.firebasestorage.app',
    iosBundleId: 'com.example.word',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Cqz1MrGOCbgErldRb3pOiTwCixVCbTM',
    appId: '1:974845475666:ios:9991351c2c09091a25d88b',
    messagingSenderId: '974845475666',
    projectId: 'wordquiz-8ca30',
    storageBucket: 'wordquiz-8ca30.firebasestorage.app',
    iosBundleId: 'com.example.word',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrmRiD0qoDwr5vln_jeoE3ranwdOuceHE',
    appId: '1:974845475666:web:0c7aea9f1f8e2c1d25d88b',
    messagingSenderId: '974845475666',
    projectId: 'wordquiz-8ca30',
    authDomain: 'wordquiz-8ca30.firebaseapp.com',
    storageBucket: 'wordquiz-8ca30.firebasestorage.app',
    measurementId: 'G-4J4EGDCV4B',
  );
}
